import { NextRequest, NextResponse } from 'next/server';

// Full workflow templates with real SerializedWorkflow definitions

const TEMPLATES = [
  {
    id: 'daily-content-brief',
    name: 'Daily Content Brief',
    description: 'AI agent researches daily topics and posts a formatted brief',
    category: 'ai',
    icon: 'Bot',
    tags: ['ai', 'content', 'schedule', 'daily'],
    workflow: {
      version: '1',
      blocks: [
        {
          id: 'starter-1', position: { x: 0, y: 200 },
          config: { tool: 'starter', params: { triggerType: 'schedule', schedule: '0 9 * * *' } },
          inputs: {}, outputs: {},
          metadata: { id: 'starter-1', name: 'Daily Trigger', icon: 'Zap', color: '#22c55e', category: 'trigger' },
          enabled: true,
        },
        {
          id: 'agent-1', position: { x: 300, y: 200 },
          config: {
            tool: 'agent',
            params: {
              model: 'claude-sonnet-4-20250514',
              systemPrompt: "You are a research specialist. Research today's trending topics, notable updates, and market-moving events. Focus on actionable insights.\n\nOutput Format:\n1. Top Headlines (3-5 bullet points)\n2. Trending Narratives (2-3 themes)\n3. Notable Activity\n4. Upcoming Events (next 48h)\n5. Key Takeaway (1-2 sentences)",
              userPrompt: "Generate today's content brief.",
              temperature: '0.4',
              maxTokens: '4096',
            },
          },
          inputs: { messages: 'json' }, outputs: { content: 'string' },
          metadata: { id: 'agent-1', name: 'Research Agent', icon: 'Bot', color: '#a78bfa', category: 'ai' },
          enabled: true,
        },
        {
          id: 'func-1', position: { x: 600, y: 200 },
          config: {
            tool: 'function',
            params: {
              code: "const content = $.input;\nconst now = new Date().toISOString().split('T')[0];\n\nconst formatted = [\n  '# Daily Content Brief — ' + now,\n  '',\n  content,\n  '',\n  '---',\n  '*Generated automatically by Mission Control*',\n].join('\\n');\n\nreturn { markdown: formatted, date: now };",
            },
          },
          inputs: { code: 'string' }, outputs: { result: 'json' },
          metadata: { id: 'func-1', name: 'Format Brief', icon: 'Code', color: '#60a5fa', category: 'logic' },
          enabled: true,
        },
        {
          id: 'slack-1', position: { x: 900, y: 200 },
          config: { tool: 'slack', params: { channel: '#content', message: '{{input.markdown}}', webhookUrl: '' } },
          inputs: { text: 'string' }, outputs: { data: 'json' },
          metadata: { id: 'slack-1', name: 'Post to Slack', icon: 'MessageSquare', color: '#e879f9', category: 'integration' },
          enabled: true,
        },
      ],
      connections: [
        { source: 'starter-1', target: 'agent-1' },
        { source: 'agent-1', target: 'func-1' },
        { source: 'func-1', target: 'slack-1' },
      ],
      loops: {},
    },
  },
  {
    id: 'webhook-slack-notify',
    name: 'Webhook to Slack',
    description: 'Receives webhooks and forwards formatted notifications to Slack',
    category: 'notification',
    icon: 'MessageSquare',
    tags: ['webhook', 'slack', 'notification'],
    workflow: {
      version: '1',
      blocks: [
        {
          id: 'starter-1', position: { x: 0, y: 200 },
          config: { tool: 'starter', params: { triggerType: 'webhook', webhookPath: '/webhook/notify' } },
          inputs: {}, outputs: {},
          metadata: { id: 'starter-1', name: 'Webhook Trigger', icon: 'Zap', color: '#22c55e', category: 'trigger' },
          enabled: true,
        },
        {
          id: 'func-1', position: { x: 300, y: 200 },
          config: {
            tool: 'function',
            params: {
              code: "const payload = $.input;\nconst eventType = payload?.event || payload?.type || 'unknown';\nconst message = payload?.message || payload?.text || JSON.stringify(payload);\nconst source = payload?.source || 'External Service';\nconst timestamp = new Date().toLocaleString('en-US', { timeZone: 'UTC' });\n\nreturn {\n  text: '*[' + source + '] ' + eventType + '*\\n\\n' + message + '\\n\\n_Received at ' + timestamp + ' UTC_',\n  eventType,\n  source,\n};",
            },
          },
          inputs: { code: 'string' }, outputs: { result: 'json' },
          metadata: { id: 'func-1', name: 'Parse & Format', icon: 'Code', color: '#60a5fa', category: 'logic' },
          enabled: true,
        },
        {
          id: 'slack-1', position: { x: 600, y: 200 },
          config: { tool: 'slack', params: { channel: '#notifications', message: '{{input.text}}', webhookUrl: '' } },
          inputs: { text: 'string' }, outputs: { data: 'json' },
          metadata: { id: 'slack-1', name: 'Slack Notify', icon: 'MessageSquare', color: '#e879f9', category: 'integration' },
          enabled: true,
        },
      ],
      connections: [
        { source: 'starter-1', target: 'func-1' },
        { source: 'func-1', target: 'slack-1' },
      ],
      loops: {},
    },
  },
  {
    id: 'weekly-report',
    name: 'Weekly Report Generator',
    description: 'Weekly data fetch and AI-powered report generation',
    category: 'reporting',
    icon: 'FileText',
    tags: ['report', 'ai', 'weekly', 'analytics'],
    workflow: {
      version: '1',
      blocks: [
        {
          id: 'starter-1', position: { x: 0, y: 200 },
          config: { tool: 'starter', params: { triggerType: 'schedule', schedule: '0 9 * * 1' } },
          inputs: {}, outputs: {},
          metadata: { id: 'starter-1', name: 'Weekly Trigger', icon: 'Zap', color: '#22c55e', category: 'trigger' },
          enabled: true,
        },
        {
          id: 'api-1', position: { x: 300, y: 200 },
          config: {
            tool: 'api',
            params: { method: 'GET', url: 'https://your-api.example.com/analytics/weekly', headers: '{"Authorization": "Bearer {{API_TOKEN}}"}', body: '' },
          },
          inputs: { url: 'string' }, outputs: { data: 'json' },
          metadata: { id: 'api-1', name: 'Fetch Data', icon: 'Globe', color: '#f97316', category: 'integration' },
          enabled: true,
        },
        {
          id: 'agent-1', position: { x: 600, y: 200 },
          config: {
            tool: 'agent',
            params: {
              model: 'claude-sonnet-4-20250514',
              systemPrompt: "You are a data analyst. Given raw analytics data, produce a structured weekly summary.\n\nOutput Format:\n1. Executive Summary (2-3 sentences)\n2. Key Metrics (bullet list with week-over-week change)\n3. Highlights (3-5 notable trends)\n4. Concerns (anything requiring attention)\n5. Recommendations (1-3 actionable steps)",
              userPrompt: 'Analyze the following weekly data and write a summary report:\n\n{{input}}',
              temperature: '0.3',
              maxTokens: '4096',
            },
          },
          inputs: { messages: 'json' }, outputs: { content: 'string' },
          metadata: { id: 'agent-1', name: 'Report Writer', icon: 'Bot', color: '#a78bfa', category: 'ai' },
          enabled: true,
        },
        {
          id: 'response-1', position: { x: 900, y: 200 },
          config: { tool: 'response', params: { outputKey: 'report', template: '{{input}}' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'response-1', name: 'Output Report', icon: 'ArrowRight', color: '#4ade80', category: 'utility' },
          enabled: true,
        },
      ],
      connections: [
        { source: 'starter-1', target: 'api-1' },
        { source: 'api-1', target: 'agent-1' },
        { source: 'agent-1', target: 'response-1' },
      ],
      loops: {},
    },
  },
  {
    id: 'api-health-monitor',
    name: 'API Health Monitor',
    description: 'Periodically checks API endpoints and alerts on failures',
    category: 'automation',
    icon: 'Activity',
    tags: ['monitoring', 'api', 'alerts', 'schedule'],
    workflow: {
      version: '1',
      blocks: [
        {
          id: 'starter-1', position: { x: 0, y: 200 },
          config: { tool: 'starter', params: { triggerType: 'schedule', schedule: '*/15 * * * *' } },
          inputs: {}, outputs: {},
          metadata: { id: 'starter-1', name: 'Health Check Trigger', icon: 'Zap', color: '#22c55e', category: 'trigger' },
          enabled: true,
        },
        {
          id: 'api-1', position: { x: 300, y: 200 },
          config: { tool: 'api', params: { method: 'GET', url: 'https://your-service.example.com/api/health', headers: '{}', body: '' } },
          inputs: { url: 'string' }, outputs: { data: 'json', status: 'number' },
          metadata: { id: 'api-1', name: 'Check Health', icon: 'Globe', color: '#f97316', category: 'integration' },
          enabled: true,
        },
        {
          id: 'func-1', position: { x: 600, y: 200 },
          config: {
            tool: 'function',
            params: {
              code: "const status = $.input?.status || 0;\nconst isHealthy = status >= 200 && status < 300;\nreturn {\n  healthy: isHealthy,\n  status: status,\n  timestamp: new Date().toISOString(),\n  details: isHealthy ? 'Service OK (HTTP ' + status + ')' : 'Service returned HTTP ' + status,\n};",
            },
          },
          inputs: { code: 'string' }, outputs: { result: 'json' },
          metadata: { id: 'func-1', name: 'Evaluate Status', icon: 'Code', color: '#60a5fa', category: 'logic' },
          enabled: true,
        },
        {
          id: 'condition-1', position: { x: 900, y: 200 },
          config: { tool: 'condition', params: { condition: '$.input.healthy === false', trueLabel: 'Unhealthy', falseLabel: 'Healthy' } },
          inputs: {}, outputs: {},
          metadata: { id: 'condition-1', name: 'Is Unhealthy?', icon: 'GitBranch', color: '#fbbf24', category: 'logic' },
          enabled: true,
        },
        {
          id: 'slack-1', position: { x: 1200, y: 100 },
          config: { tool: 'slack', params: { channel: '#alerts', message: '*API Health Alert*\nStatus: {{input.status}}\nDetails: {{input.details}}\nTime: {{input.timestamp}}', webhookUrl: '' } },
          inputs: { text: 'string' }, outputs: { data: 'json' },
          metadata: { id: 'slack-1', name: 'Send Alert', icon: 'MessageSquare', color: '#e879f9', category: 'integration' },
          enabled: true,
        },
        {
          id: 'response-1', position: { x: 1200, y: 350 },
          config: { tool: 'response', params: { outputKey: 'result', template: 'Health check passed' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'response-1', name: 'Log OK', icon: 'ArrowRight', color: '#4ade80', category: 'utility' },
          enabled: true,
        },
      ],
      connections: [
        { source: 'starter-1', target: 'api-1' },
        { source: 'api-1', target: 'func-1' },
        { source: 'func-1', target: 'condition-1' },
        { source: 'condition-1', target: 'slack-1', sourceHandle: 'true' },
        { source: 'condition-1', target: 'response-1', sourceHandle: 'false' },
      ],
      loops: {},
    },
  },
  {
    id: 'content-review',
    name: 'Content Review Pipeline',
    description: 'AI-powered content review with pass/fail routing',
    category: 'ai',
    icon: 'CheckCircle',
    tags: ['ai', 'review', 'quality', 'content'],
    workflow: {
      version: '1',
      blocks: [
        {
          id: 'starter-1', position: { x: 0, y: 200 },
          config: { tool: 'starter', params: { triggerType: 'manual' } },
          inputs: {}, outputs: {},
          metadata: { id: 'starter-1', name: 'Submit Content', icon: 'Zap', color: '#22c55e', category: 'trigger' },
          enabled: true,
        },
        {
          id: 'agent-1', position: { x: 300, y: 200 },
          config: {
            tool: 'agent',
            params: {
              model: 'claude-sonnet-4-20250514',
              systemPrompt: "You are an expert content reviewer. Evaluate the provided content for quality, accuracy, tone, grammar, and engagement.\n\nScore each criterion 0-10:\n- Accuracy: Are claims factual?\n- Clarity: Is it clear and easy to follow?\n- Tone: Is the tone appropriate?\n- Grammar: Any grammatical errors?\n- Engagement: Is it compelling?\n\nReturn: overallScore (average), passed (true if >= 7), summary, issues[], suggestions[]",
              userPrompt: 'Review this content:\n\n{{input}}',
              temperature: '0.2',
              maxTokens: '4096',
            },
          },
          inputs: { messages: 'json' }, outputs: { content: 'string' },
          metadata: { id: 'agent-1', name: 'Content Reviewer', icon: 'Bot', color: '#a78bfa', category: 'ai' },
          enabled: true,
        },
        {
          id: 'func-1', position: { x: 600, y: 200 },
          config: {
            tool: 'function',
            params: {
              code: "const review = $.input;\nconst passed = review?.overallScore >= 7 || review?.passed === true;\nreturn {\n  passed,\n  overallScore: review?.overallScore || 0,\n  summary: review?.summary || 'No summary',\n  issues: review?.issues || [],\n  suggestions: review?.suggestions || [],\n};",
            },
          },
          inputs: { code: 'string' }, outputs: { result: 'json' },
          metadata: { id: 'func-1', name: 'Parse Review', icon: 'Code', color: '#60a5fa', category: 'logic' },
          enabled: true,
        },
        {
          id: 'condition-1', position: { x: 900, y: 200 },
          config: { tool: 'condition', params: { condition: '$.input.passed === true', trueLabel: 'Approved', falseLabel: 'Revision Needed' } },
          inputs: {}, outputs: {},
          metadata: { id: 'condition-1', name: 'Pass/Fail?', icon: 'GitBranch', color: '#fbbf24', category: 'logic' },
          enabled: true,
        },
        {
          id: 'response-pass', position: { x: 1200, y: 100 },
          config: { tool: 'response', params: { outputKey: 'result', template: 'Content approved with score {{input.overallScore}}/10' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'response-pass', name: 'Approved', icon: 'ArrowRight', color: '#4ade80', category: 'utility' },
          enabled: true,
        },
        {
          id: 'response-fail', position: { x: 1200, y: 350 },
          config: { tool: 'response', params: { outputKey: 'result', template: 'Content needs revision — score {{input.overallScore}}/10' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'response-fail', name: 'Revision Needed', icon: 'ArrowRight', color: '#ef4444', category: 'utility' },
          enabled: true,
        },
      ],
      connections: [
        { source: 'starter-1', target: 'agent-1' },
        { source: 'agent-1', target: 'func-1' },
        { source: 'func-1', target: 'condition-1' },
        { source: 'condition-1', target: 'response-pass', sourceHandle: 'true' },
        { source: 'condition-1', target: 'response-fail', sourceHandle: 'false' },
      ],
      loops: {},
    },
  },
  {
    id: 'data-transform',
    name: 'Data Transform Pipeline',
    description: 'Validates, transforms, and forwards data between APIs',
    category: 'data',
    icon: 'ArrowRightLeft',
    tags: ['data', 'transform', 'api', 'pipeline'],
    workflow: {
      version: '1',
      blocks: [
        {
          id: 'starter-1', position: { x: 0, y: 200 },
          config: { tool: 'starter', params: { triggerType: 'api' } },
          inputs: {}, outputs: {},
          metadata: { id: 'starter-1', name: 'Receive Data', icon: 'Zap', color: '#22c55e', category: 'trigger' },
          enabled: true,
        },
        {
          id: 'func-1', position: { x: 300, y: 200 },
          config: {
            tool: 'function',
            params: {
              code: "const input = $.input;\nconst errors = [];\nif (!input) errors.push('Input is empty');\nif (input && !input.id) errors.push('Missing field: id');\nif (input && !input.data) errors.push('Missing field: data');\n\nif (errors.length > 0) throw new Error('Validation failed: ' + errors.join(', '));\n\nreturn {\n  valid: true,\n  data: {\n    externalId: String(input.id),\n    payload: typeof input.data === 'string' ? JSON.parse(input.data) : input.data,\n    metadata: {\n      source: input.source || 'unknown',\n      receivedAt: new Date().toISOString(),\n    },\n  },\n};",
            },
          },
          inputs: { code: 'string' }, outputs: { result: 'json' },
          metadata: { id: 'func-1', name: 'Validate & Transform', icon: 'Code', color: '#60a5fa', category: 'logic' },
          enabled: true,
        },
        {
          id: 'api-1', position: { x: 600, y: 200 },
          config: {
            tool: 'api',
            params: { method: 'POST', url: 'https://destination-api.example.com/ingest', headers: '{"Authorization": "Bearer {{DEST_API_KEY}}", "Content-Type": "application/json"}', body: '{{input.data}}' },
          },
          inputs: { url: 'string' }, outputs: { data: 'json', status: 'number' },
          metadata: { id: 'api-1', name: 'Forward Data', icon: 'Globe', color: '#f97316', category: 'integration' },
          enabled: true,
        },
        {
          id: 'response-1', position: { x: 900, y: 200 },
          config: { tool: 'response', params: { outputKey: 'result', template: '{{input}}' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'response-1', name: 'Output Result', icon: 'ArrowRight', color: '#4ade80', category: 'utility' },
          enabled: true,
        },
      ],
      connections: [
        { source: 'starter-1', target: 'func-1' },
        { source: 'func-1', target: 'api-1' },
        { source: 'api-1', target: 'response-1' },
      ],
      loops: {},
    },
  },
  // ── MC-Focused Templates ──────────────────────────────────

  {
    id: 'agent-task-pipeline',
    name: 'Agent Task Pipeline',
    description: 'Create a task, assign it to an agent, notify them, and track completion',
    category: 'mc-actions',
    tags: ['tasks', 'agents', 'automation'],
    state: {
      version: '1',
      blocks: [
        {
          id: 'trigger-1', position: { x: 100, y: 200 },
          config: { tool: 'starter', params: { triggerType: 'manual' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'trigger-1', name: 'Manual Trigger', icon: 'Zap', color: '#22c55e', category: 'trigger' },
          enabled: true,
        },
        {
          id: 'agent-plan', position: { x: 400, y: 200 },
          config: { tool: 'agent', params: { model: 'gemini-2.5-flash', systemPrompt: 'You are a project planner. Given a goal, break it into actionable subtasks. Return JSON: { "title": "...", "description": "...", "subtasks": ["step 1", "step 2", ...] }', userPrompt: '{{input}}', temperature: '0.4' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'agent-plan', name: 'Plan Task', icon: 'Bot', color: '#a78bfa', category: 'ai' },
          enabled: true,
        },
        {
          id: 'func-parse', position: { x: 700, y: 200 },
          config: { tool: 'function', params: { code: 'const input = $.input;\ntry {\n  const parsed = JSON.parse(input.replace(/```json?\\n?/g, "").replace(/```/g, "").trim());\n  return parsed;\n} catch {\n  return { title: "New Task", description: input, subtasks: [] };\n}' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'func-parse', name: 'Parse Plan', icon: 'Code', color: '#60a5fa', category: 'logic' },
          enabled: true,
        },
        {
          id: 'create-task', position: { x: 1000, y: 200 },
          config: { tool: 'create_task', params: { title: '{{input.title}}', description: '{{input.description}}', planningNotes: 'Auto-created by workflow', priority: 'p2', subtasks: '{{input.subtasks}}' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'create-task', name: 'Create Task', icon: 'CheckCircle', color: '#22c55e', category: 'integration' },
          enabled: true,
        },
      ],
      connections: [
        { source: 'trigger-1', target: 'agent-plan' },
        { source: 'agent-plan', target: 'func-parse' },
        { source: 'func-parse', target: 'create-task' },
      ],
      loops: {},
    },
  },
  {
    id: 'content-to-social',
    name: 'AI Content to X/Twitter',
    description: 'Generate social media content with AI, run it through guardrails, then post to X',
    category: 'social',
    tags: ['x', 'twitter', 'social', 'ai', 'content'],
    state: {
      version: '1',
      blocks: [
        {
          id: 'trigger-1', position: { x: 100, y: 200 },
          config: { tool: 'starter', params: { triggerType: 'manual' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'trigger-1', name: 'Manual Trigger', icon: 'Zap', color: '#22c55e', category: 'trigger' },
          enabled: true,
        },
        {
          id: 'agent-write', position: { x: 400, y: 200 },
          config: { tool: 'agent', params: { model: 'gemini-2.5-flash', systemPrompt: 'You are a social media copywriter. Write engaging tweets (max 280 chars). No hashtag spam. Be authentic and conversational. Return only the tweet text, nothing else.', userPrompt: 'Write a tweet about: {{input}}', temperature: '0.8' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'agent-write', name: 'Write Tweet', icon: 'Bot', color: '#a78bfa', category: 'ai' },
          enabled: true,
        },
        {
          id: 'guard-check', position: { x: 700, y: 200 },
          config: { tool: 'guardrails', params: { rules: 'No offensive language\nNo misleading claims\nNo competitor attacks\nMust be under 280 characters\nNo excessive hashtags (max 2)', action: 'block' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'guard-check', name: 'Content Check', icon: 'Shield', color: '#ef4444', category: 'ai' },
          enabled: true,
        },
        {
          id: 'condition-safe', position: { x: 1000, y: 200 },
          config: { tool: 'condition', params: { condition: '$.input && !$.input.blocked', trueLabel: 'Safe', falseLabel: 'Blocked' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'condition-safe', name: 'Safe to Post?', icon: 'GitBranch', color: '#fbbf24', category: 'logic' },
          enabled: true,
        },
        {
          id: 'x-post', position: { x: 1300, y: 100 },
          config: { tool: 'x_twitter', params: { operation: 'post_tweet', content: '{{guard-check.input}}' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'x-post', name: 'Post to X', icon: 'AtSign', color: '#000000', category: 'integration' },
          enabled: true,
        },
        {
          id: 'notify-blocked', position: { x: 1300, y: 300 },
          config: { tool: 'response', params: { template: 'Content blocked by guardrails: {{guard-check.violations}}' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'notify-blocked', name: 'Blocked Notice', icon: 'ArrowRight', color: '#ef4444', category: 'utility' },
          enabled: true,
        },
      ],
      connections: [
        { source: 'trigger-1', target: 'agent-write' },
        { source: 'agent-write', target: 'guard-check' },
        { source: 'guard-check', target: 'condition-safe' },
        { source: 'condition-safe', target: 'x-post', sourceHandle: 'true' },
        { source: 'condition-safe', target: 'notify-blocked', sourceHandle: 'false' },
      ],
      loops: {},
    },
  },
  {
    id: 'multi-agent-review',
    name: 'Multi-Agent Content Review',
    description: 'One agent writes content, another evaluates it, human approves if score is high enough',
    category: 'ai',
    tags: ['agents', 'review', 'evaluation', 'approval'],
    state: {
      version: '1',
      blocks: [
        {
          id: 'trigger-1', position: { x: 100, y: 200 },
          config: { tool: 'starter', params: { triggerType: 'manual' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'trigger-1', name: 'Manual Trigger', icon: 'Zap', color: '#22c55e', category: 'trigger' },
          enabled: true,
        },
        {
          id: 'agent-writer', position: { x: 400, y: 200 },
          config: { tool: 'agent', params: { model: 'gemini-2.5-flash', systemPrompt: 'You are an expert content writer. Write high-quality, engaging content.', userPrompt: '{{input}}', temperature: '0.7' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'agent-writer', name: 'Writer Agent', icon: 'Bot', color: '#a78bfa', category: 'ai' },
          enabled: true,
        },
        {
          id: 'evaluator-1', position: { x: 700, y: 200 },
          config: { tool: 'evaluator', params: { criteria: 'Clarity, accuracy, engagement, grammar, and completeness', rubric: '0-3: Poor, 4-6: Acceptable, 7-9: Good, 10: Excellent', model: 'gemini-2.5-flash' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'evaluator-1', name: 'Quality Check', icon: 'CheckCircle', color: '#14b8a6', category: 'ai' },
          enabled: true,
        },
        {
          id: 'condition-quality', position: { x: 1000, y: 200 },
          config: { tool: 'condition', params: { condition: '$.input && $.input.score >= 7', trueLabel: 'High Quality', falseLabel: 'Needs Work' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'condition-quality', name: 'Quality Gate', icon: 'GitBranch', color: '#fbbf24', category: 'logic' },
          enabled: true,
        },
        {
          id: 'approval-1', position: { x: 1300, y: 100 },
          config: { tool: 'human_in_the_loop', params: { prompt: 'Content passed quality check (score: {{evaluator-1.score}}/10). Review and approve:\n\n{{agent-writer.response}}' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'approval-1', name: 'Human Review', icon: 'Hand', color: '#f97316', category: 'utility' },
          enabled: true,
        },
        {
          id: 'save-draft', position: { x: 1300, y: 300 },
          config: { tool: 'save_to_library', params: { folder: 'drafts', filename: 'draft-{{date}}.md', content: 'Score: {{evaluator-1.score}}/10\nFeedback: {{evaluator-1.feedback}}\n\n---\n\n{{agent-writer.response}}' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'save-draft', name: 'Save Draft', icon: 'FileText', color: '#14b8a6', category: 'integration' },
          enabled: true,
        },
      ],
      connections: [
        { source: 'trigger-1', target: 'agent-writer' },
        { source: 'agent-writer', target: 'evaluator-1' },
        { source: 'evaluator-1', target: 'condition-quality' },
        { source: 'condition-quality', target: 'approval-1', sourceHandle: 'true' },
        { source: 'condition-quality', target: 'save-draft', sourceHandle: 'false' },
      ],
      loops: {},
    },
  },
  {
    id: 'github-issue-triage',
    name: 'GitHub Issue Triage',
    description: 'Fetch new GitHub issues, use AI to categorize and prioritize, create MC tasks',
    category: 'integration',
    tags: ['github', 'issues', 'triage', 'tasks'],
    state: {
      version: '1',
      blocks: [
        {
          id: 'trigger-1', position: { x: 100, y: 200 },
          config: { tool: 'starter', params: { triggerType: 'schedule', schedule: '0 */4 * * *' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'trigger-1', name: 'Every 4 Hours', icon: 'Zap', color: '#22c55e', category: 'trigger' },
          enabled: true,
        },
        {
          id: 'gh-issues', position: { x: 400, y: 200 },
          config: { tool: 'github', params: { action: 'list-issues', repo: 'your-org/your-repo' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'gh-issues', name: 'Fetch Issues', icon: 'Github', color: '#6b7280', category: 'integration' },
          enabled: true,
        },
        {
          id: 'agent-triage', position: { x: 700, y: 200 },
          config: { tool: 'agent', params: { model: 'gemini-2.5-flash', systemPrompt: 'You are a project manager. Given a list of GitHub issues, categorize each as: bug, feature, question, or chore. Assign priority: p0 (critical), p1 (high), p2 (medium), p3 (low). Return JSON array: [{ "number": N, "title": "...", "category": "...", "priority": "p0-p3", "summary": "one-line" }]', userPrompt: 'Triage these issues:\n{{input}}', temperature: '0.3' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'agent-triage', name: 'AI Triage', icon: 'Bot', color: '#a78bfa', category: 'ai' },
          enabled: true,
        },
        {
          id: 'save-report', position: { x: 1000, y: 200 },
          config: { tool: 'save_to_library', params: { folder: 'reports', filename: 'issue-triage-{{date}}.md', content: '# Issue Triage Report\n\n{{input}}' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'save-report', name: 'Save Report', icon: 'FileText', color: '#14b8a6', category: 'integration' },
          enabled: true,
        },
      ],
      connections: [
        { source: 'trigger-1', target: 'gh-issues' },
        { source: 'gh-issues', target: 'agent-triage' },
        { source: 'agent-triage', target: 'save-report' },
      ],
      loops: {},
    },
  },
  {
    id: 'daily-standup-digest',
    name: 'Daily Standup Digest',
    description: 'Gather task updates, generate a team standup summary, post to Slack and save to library',
    category: 'mc-actions',
    tags: ['standup', 'daily', 'slack', 'report'],
    state: {
      version: '1',
      blocks: [
        {
          id: 'trigger-1', position: { x: 100, y: 200 },
          config: { tool: 'starter', params: { triggerType: 'schedule', schedule: '0 9 * * 1-5' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'trigger-1', name: 'Weekdays 9am', icon: 'Zap', color: '#22c55e', category: 'trigger' },
          enabled: true,
        },
        {
          id: 'api-tasks', position: { x: 400, y: 200 },
          config: { tool: 'api', params: { method: 'GET', url: '/api/tasks?status=in-progress,review' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'api-tasks', name: 'Fetch Active Tasks', icon: 'Globe', color: '#f97316', category: 'integration' },
          enabled: true,
        },
        {
          id: 'agent-digest', position: { x: 700, y: 200 },
          config: { tool: 'agent', params: { model: 'gemini-2.5-flash', systemPrompt: 'You are a standup facilitator. Given active tasks, write a brief team standup digest with sections: In Progress, In Review, Blockers (if any). Keep it concise and actionable. Use bullet points.', userPrompt: 'Generate standup from these active tasks:\n{{input}}', temperature: '0.4' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'agent-digest', name: 'Generate Digest', icon: 'Bot', color: '#a78bfa', category: 'ai' },
          enabled: true,
        },
        {
          id: 'slack-post', position: { x: 1000, y: 100 },
          config: { tool: 'slack', params: { channel: '#standup', message: '*Daily Standup — {{date}}*\n\n{{input}}', webhookUrl: '' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'slack-post', name: 'Post to Slack', icon: 'MessageSquare', color: '#e879f9', category: 'integration' },
          enabled: true,
        },
        {
          id: 'save-standup', position: { x: 1000, y: 300 },
          config: { tool: 'save_to_library', params: { folder: 'standups', filename: 'standup-{{date}}.md', content: '# Standup — {{date}}\n\n{{input}}' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'save-standup', name: 'Save to Library', icon: 'FileText', color: '#14b8a6', category: 'integration' },
          enabled: true,
        },
      ],
      connections: [
        { source: 'trigger-1', target: 'api-tasks' },
        { source: 'api-tasks', target: 'agent-digest' },
        { source: 'agent-digest', target: 'slack-post' },
        { source: 'agent-digest', target: 'save-standup' },
      ],
      loops: {},
    },
  },
  {
    id: 'competitor-monitor',
    name: 'Competitor Intelligence Monitor',
    description: 'Search for competitor mentions, analyze sentiment with AI, send digest to email',
    category: 'data',
    tags: ['search', 'competitive', 'intelligence', 'email'],
    state: {
      version: '1',
      blocks: [
        {
          id: 'trigger-1', position: { x: 100, y: 200 },
          config: { tool: 'starter', params: { triggerType: 'schedule', schedule: '0 8 * * 1-5' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'trigger-1', name: 'Weekdays 8am', icon: 'Zap', color: '#22c55e', category: 'trigger' },
          enabled: true,
        },
        {
          id: 'search-comp', position: { x: 400, y: 200 },
          config: { tool: 'search', params: { query: 'competitor-name latest news announcements features', engine: 'perplexity' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'search-comp', name: 'Search News', icon: 'Search', color: '#f97316', category: 'data' },
          enabled: true,
        },
        {
          id: 'agent-analyze', position: { x: 700, y: 200 },
          config: { tool: 'agent', params: { model: 'gemini-2.5-flash', systemPrompt: 'You are a competitive intelligence analyst. Analyze mentions and news about competitors. Identify: new features, pricing changes, partnerships, funding, sentiment. Write a brief executive summary with key takeaways and implications for our business.', userPrompt: 'Analyze this competitive intelligence:\n\n{{input}}', temperature: '0.4' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'agent-analyze', name: 'Analyze Intel', icon: 'Bot', color: '#a78bfa', category: 'ai' },
          enabled: true,
        },
        {
          id: 'email-report', position: { x: 1000, y: 200 },
          config: { tool: 'send_email_mc', params: { to: 'team@company.com', subject: 'Competitive Intel Digest — {{date}}', body: '{{input}}' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'email-report', name: 'Email Report', icon: 'Mail', color: '#fb7185', category: 'integration' },
          enabled: true,
        },
      ],
      connections: [
        { source: 'trigger-1', target: 'search-comp' },
        { source: 'search-comp', target: 'agent-analyze' },
        { source: 'agent-analyze', target: 'email-report' },
      ],
      loops: {},
    },
  },
  {
    id: 'onboarding-workflow',
    name: 'New User Onboarding',
    description: 'Webhook triggers welcome email, creates onboarding task, notifies assigned agent',
    category: 'mc-actions',
    tags: ['onboarding', 'webhook', 'tasks', 'email'],
    state: {
      version: '1',
      blocks: [
        {
          id: 'trigger-1', position: { x: 100, y: 200 },
          config: { tool: 'starter', params: { triggerType: 'webhook', webhookPath: '/webhook/new-user' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'trigger-1', name: 'New User Webhook', icon: 'Zap', color: '#22c55e', category: 'trigger' },
          enabled: true,
        },
        {
          id: 'func-parse', position: { x: 400, y: 200 },
          config: { tool: 'function', params: { code: 'const input = $.input;\nconst name = input?.name || "New User";\nconst email = input?.email || "";\nreturn { name, email, greeting: `Welcome aboard, ${name}!` };' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'func-parse', name: 'Parse User', icon: 'Code', color: '#60a5fa', category: 'logic' },
          enabled: true,
        },
        {
          id: 'email-welcome', position: { x: 700, y: 100 },
          config: { tool: 'send_email_mc', params: { to: '{{input.email}}', subject: '{{input.greeting}}', body: 'Hi {{input.name}},\n\nWelcome to the platform! Your account is ready.\n\nHere are some resources to get started:\n- Quick Start Guide\n- FAQ\n- Support: support@company.com\n\nBest,\nThe Team' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'email-welcome', name: 'Welcome Email', icon: 'Mail', color: '#fb7185', category: 'integration' },
          enabled: true,
        },
        {
          id: 'create-onboard-task', position: { x: 700, y: 300 },
          config: { tool: 'create_task', params: { title: 'Onboard: {{input.name}}', description: 'Complete onboarding for {{input.name}} ({{input.email}})', planningNotes: 'Auto-created by onboarding workflow', priority: 'p2', subtasks: 'Send welcome package\nSchedule intro call\nAdd to team channels\nShare documentation' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'create-onboard-task', name: 'Create Task', icon: 'CheckCircle', color: '#22c55e', category: 'integration' },
          enabled: true,
        },
      ],
      connections: [
        { source: 'trigger-1', target: 'func-parse' },
        { source: 'func-parse', target: 'email-welcome' },
        { source: 'func-parse', target: 'create-onboard-task' },
      ],
      loops: {},
    },
  },
  {
    id: 'x-engagement-monitor',
    name: 'X/Twitter Engagement Monitor',
    description: 'Search for brand mentions on X, analyze sentiment, generate AI-powered reply suggestions',
    category: 'social',
    tags: ['x', 'twitter', 'engagement', 'sentiment', 'social'],
    state: {
      version: '1',
      blocks: [
        {
          id: 'trigger-1', position: { x: 100, y: 200 },
          config: { tool: 'starter', params: { triggerType: 'schedule', schedule: '0 */2 * * *' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'trigger-1', name: 'Every 2 Hours', icon: 'Zap', color: '#22c55e', category: 'trigger' },
          enabled: true,
        },
        {
          id: 'x-search', position: { x: 400, y: 200 },
          config: { tool: 'x_twitter', params: { operation: 'search_tweets', query: '@yourbrand OR "your brand name" -is:retweet', maxResults: '10' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'x-search', name: 'Search Mentions', icon: 'AtSign', color: '#000000', category: 'integration' },
          enabled: true,
        },
        {
          id: 'agent-sentiment', position: { x: 700, y: 200 },
          config: { tool: 'agent', params: { model: 'gemini-2.5-flash', systemPrompt: 'You are a social media analyst. For each tweet mention, determine: sentiment (positive/neutral/negative), urgency (high/low), and draft a brief reply suggestion. Return JSON array: [{ "text": "original tweet", "sentiment": "positive", "urgency": "low", "suggestedReply": "..." }]', userPrompt: 'Analyze these brand mentions:\n{{input}}', temperature: '0.3' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'agent-sentiment', name: 'Sentiment Analysis', icon: 'Bot', color: '#a78bfa', category: 'ai' },
          enabled: true,
        },
        {
          id: 'save-analysis', position: { x: 1000, y: 200 },
          config: { tool: 'save_to_library', params: { folder: 'social-reports', filename: 'x-mentions-{{date}}.md', content: '# X Mentions Report — {{date}}\n\n{{input}}' } },
          inputs: {}, outputs: { response: 'string' },
          metadata: { id: 'save-analysis', name: 'Save Report', icon: 'FileText', color: '#14b8a6', category: 'integration' },
          enabled: true,
        },
      ],
      connections: [
        { source: 'trigger-1', target: 'x-search' },
        { source: 'x-search', target: 'agent-sentiment' },
        { source: 'agent-sentiment', target: 'save-analysis' },
      ],
      loops: {},
    },
  },
];

export async function GET(req: NextRequest) {
  const id = req.nextUrl.searchParams.get('id');
  if (id) {
    const t = TEMPLATES.find((t) => t.id === id);
    if (!t) return NextResponse.json({ error: 'Template not found' }, { status: 404 });
    return NextResponse.json(t);
  }
  return NextResponse.json({ templates: TEMPLATES });
}
