import { browserUseRunTaskTool } from '@/tools/browser_use'
import {
  discordAddReactionTool,
  discordArchiveThreadTool,
  discordAssignRoleTool,
  discordBanMemberTool,
  discordCreateChannelTool,
  discordCreateInviteTool,
  discordCreateRoleTool,
  discordCreateThreadTool,
  discordCreateWebhookTool,
  discordDeleteChannelTool,
  discordDeleteInviteTool,
  discordDeleteMessageTool,
  discordDeleteRoleTool,
  discordDeleteWebhookTool,
  discordEditMessageTool,
  discordExecuteWebhookTool,
  discordGetChannelTool,
  discordGetInviteTool,
  discordGetMemberTool,
  discordGetMessagesTool,
  discordGetServerTool,
  discordGetUserTool,
  discordGetWebhookTool,
  discordJoinThreadTool,
  discordKickMemberTool,
  discordLeaveThreadTool,
  discordPinMessageTool,
  discordRemoveReactionTool,
  discordRemoveRoleTool,
  discordSendMessageTool,
  discordUnbanMemberTool,
  discordUnpinMessageTool,
  discordUpdateChannelTool,
  discordUpdateMemberTool,
  discordUpdateRoleTool,
} from '@/tools/discord'
import { elevenLabsTtsTool } from '@/tools/elevenlabs'
import {
  exaAnswerTool,
  exaFindSimilarLinksTool,
  exaGetContentsTool,
  exaResearchTool,
  exaSearchTool,
} from '@/tools/exa'
import { fileParserV2Tool, fileParserV3Tool, fileParseTool } from '@/tools/file'
import {
  firecrawlAgentTool,
  firecrawlCrawlTool,
  firecrawlExtractTool,
  firecrawlMapTool,
  firecrawlScrapeTool,
  firecrawlSearchTool,
} from '@/tools/firecrawl'
import { functionExecuteTool } from '@/tools/function'
import {
  githubAddAssigneesTool,
  githubAddAssigneesV2Tool,
  githubAddLabelsTool,
  githubAddLabelsV2Tool,
  githubCancelWorkflowRunTool,
  githubCancelWorkflowRunV2Tool,
  githubCheckStarTool,
  githubCheckStarV2Tool,
  githubCloseIssueTool,
  githubCloseIssueV2Tool,
  githubClosePRTool,
  githubClosePRV2Tool,
  githubCommentTool,
  githubCommentV2Tool,
  githubCompareCommitsTool,
  githubCompareCommitsV2Tool,
  githubCreateBranchTool,
  githubCreateBranchV2Tool,
  githubCreateCommentReactionTool,
  githubCreateCommentReactionV2Tool,
  githubCreateFileTool,
  githubCreateFileV2Tool,
  githubCreateGistTool,
  githubCreateGistV2Tool,
  githubCreateIssueReactionTool,
  githubCreateIssueReactionV2Tool,
  githubCreateIssueTool,
  githubCreateIssueV2Tool,
  githubCreateMilestoneTool,
  githubCreateMilestoneV2Tool,
  githubCreatePRTool,
  githubCreatePRV2Tool,
  githubCreateProjectTool,
  githubCreateProjectV2Tool,
  githubCreateReleaseTool,
  githubCreateReleaseV2Tool,
  githubDeleteBranchTool,
  githubDeleteBranchV2Tool,
  githubDeleteCommentReactionTool,
  githubDeleteCommentReactionV2Tool,
  githubDeleteCommentTool,
  githubDeleteCommentV2Tool,
  githubDeleteFileTool,
  githubDeleteFileV2Tool,
  githubDeleteGistTool,
  githubDeleteGistV2Tool,
  githubDeleteIssueReactionTool,
  githubDeleteIssueReactionV2Tool,
  githubDeleteMilestoneTool,
  githubDeleteMilestoneV2Tool,
  githubDeleteProjectTool,
  githubDeleteProjectV2Tool,
  githubDeleteReleaseTool,
  githubDeleteReleaseV2Tool,
  githubForkGistTool,
  githubForkGistV2Tool,
  githubForkRepoTool,
  githubForkRepoV2Tool,
  githubGetBranchProtectionTool,
  githubGetBranchProtectionV2Tool,
  githubGetBranchTool,
  githubGetBranchV2Tool,
  githubGetCommitTool,
  githubGetCommitV2Tool,
  githubGetFileContentTool,
  githubGetFileContentV2Tool,
  githubGetGistTool,
  githubGetGistV2Tool,
  githubGetIssueTool,
  githubGetIssueV2Tool,
  githubGetMilestoneTool,
  githubGetMilestoneV2Tool,
  githubGetPRFilesTool,
  githubGetPRFilesV2Tool,
  githubGetProjectTool,
  githubGetProjectV2Tool,
  githubGetReleaseTool,
  githubGetReleaseV2Tool,
  githubGetTreeTool,
  githubGetTreeV2Tool,
  githubGetWorkflowRunTool,
  githubGetWorkflowRunV2Tool,
  githubGetWorkflowTool,
  githubGetWorkflowV2Tool,
  githubIssueCommentTool,
  githubIssueCommentV2Tool,
  githubLatestCommitTool,
  githubLatestCommitV2Tool,
  githubListBranchesTool,
  githubListBranchesV2Tool,
  githubListCommitsTool,
  githubListCommitsV2Tool,
  githubListForksTool,
  githubListForksV2Tool,
  githubListGistsTool,
  githubListGistsV2Tool,
  githubListIssueCommentsTool,
  githubListIssueCommentsV2Tool,
  githubListIssuesTool,
  githubListIssuesV2Tool,
  githubListMilestonesTool,
  githubListMilestonesV2Tool,
  githubListPRCommentsTool,
  githubListPRCommentsV2Tool,
  githubListPRsTool,
  githubListPRsV2Tool,
  githubListProjectsTool,
  githubListProjectsV2Tool,
  githubListReleasesTool,
  githubListReleasesV2Tool,
  githubListStargazersTool,
  githubListStargazersV2Tool,
  githubListWorkflowRunsTool,
  githubListWorkflowRunsV2Tool,
  githubListWorkflowsTool,
  githubListWorkflowsV2Tool,
  githubMergePRTool,
  githubMergePRV2Tool,
  githubPrTool,
  githubPrV2Tool,
  githubRemoveLabelTool,
  githubRemoveLabelV2Tool,
  githubRepoInfoTool,
  githubRepoInfoV2Tool,
  githubRequestReviewersTool,
  githubRequestReviewersV2Tool,
  githubRerunWorkflowTool,
  githubRerunWorkflowV2Tool,
  githubSearchCodeTool,
  githubSearchCodeV2Tool,
  githubSearchCommitsTool,
  githubSearchCommitsV2Tool,
  githubSearchIssuesTool,
  githubSearchIssuesV2Tool,
  githubSearchReposTool,
  githubSearchReposV2Tool,
  githubSearchUsersTool,
  githubSearchUsersV2Tool,
  githubStarGistTool,
  githubStarGistV2Tool,
  githubStarRepoTool,
  githubStarRepoV2Tool,
  githubTriggerWorkflowTool,
  githubTriggerWorkflowV2Tool,
  githubUnstarGistTool,
  githubUnstarGistV2Tool,
  githubUnstarRepoTool,
  githubUnstarRepoV2Tool,
  githubUpdateBranchProtectionTool,
  githubUpdateBranchProtectionV2Tool,
  githubUpdateCommentTool,
  githubUpdateCommentV2Tool,
  githubUpdateFileTool,
  githubUpdateFileV2Tool,
  githubUpdateGistTool,
  githubUpdateGistV2Tool,
  githubUpdateIssueTool,
  githubUpdateIssueV2Tool,
  githubUpdateMilestoneTool,
  githubUpdateMilestoneV2Tool,
  githubUpdatePRTool,
  githubUpdatePRV2Tool,
  githubUpdateProjectTool,
  githubUpdateProjectV2Tool,
  githubUpdateReleaseTool,
  githubUpdateReleaseV2Tool,
} from '@/tools/github'
import {
  gmailAddLabelTool,
  gmailAddLabelV2Tool,
  gmailArchiveTool,
  gmailArchiveV2Tool,
  gmailCreateLabelV2Tool,
  gmailDeleteDraftV2Tool,
  gmailDeleteLabelV2Tool,
  gmailDeleteTool,
  gmailDeleteV2Tool,
  gmailDraftTool,
  gmailDraftV2Tool,
  gmailGetDraftV2Tool,
  gmailGetThreadV2Tool,
  gmailListDraftsV2Tool,
  gmailListLabelsV2Tool,
  gmailListThreadsV2Tool,
  gmailMarkReadTool,
  gmailMarkReadV2Tool,
  gmailMarkUnreadTool,
  gmailMarkUnreadV2Tool,
  gmailMoveTool,
  gmailMoveV2Tool,
  gmailReadTool,
  gmailReadV2Tool,
  gmailRemoveLabelTool,
  gmailRemoveLabelV2Tool,
  gmailSearchTool,
  gmailSearchV2Tool,
  gmailSendTool,
  gmailSendV2Tool,
  gmailTrashThreadV2Tool,
  gmailUnarchiveTool,
  gmailUnarchiveV2Tool,
  gmailUntrashThreadV2Tool,
} from '@/tools/gmail'
import { guardrailsValidateTool } from '@/tools/guardrails'
import { httpRequestTool, webhookRequestTool } from '@/tools/http'
import { jinaReadUrlTool, jinaSearchTool } from '@/tools/jina'
import {
  jiraAddAttachmentTool,
  jiraAddCommentTool,
  jiraAddWatcherTool,
  jiraAddWorklogTool,
  jiraAssignIssueTool,
  jiraBulkRetrieveTool,
  jiraCreateIssueLinkTool,
  jiraDeleteAttachmentTool,
  jiraDeleteCommentTool,
  jiraDeleteIssueLinkTool,
  jiraDeleteIssueTool,
  jiraDeleteWorklogTool,
  jiraGetAttachmentsTool,
  jiraGetCommentsTool,
  jiraGetUsersTool,
  jiraGetWorklogsTool,
  jiraRemoveWatcherTool,
  jiraRetrieveTool,
  jiraSearchIssuesTool,
  jiraSearchUsersTool,
  jiraTransitionIssueTool,
  jiraUpdateCommentTool,
  jiraUpdateTool,
  jiraUpdateWorklogTool,
  jiraWriteTool,
} from '@/tools/jira'
import {
  knowledgeCreateDocumentTool,
  knowledgeDeleteChunkTool,
  knowledgeDeleteDocumentTool,
  knowledgeGetConnectorTool,
  knowledgeGetDocumentTool,
  knowledgeListChunksTool,
  knowledgeListConnectorsTool,
  knowledgeListDocumentsTool,
  knowledgeListTagsTool,
  knowledgeSearchTool,
  knowledgeTriggerSyncTool,
  knowledgeUpdateChunkTool,
  knowledgeUploadChunkTool,
  knowledgeUpsertDocumentTool,
} from '@/tools/knowledge'
import {
  linearAddLabelToIssueTool,
  linearAddLabelToProjectTool,
  linearArchiveIssueTool,
  linearArchiveLabelTool,
  linearArchiveProjectTool,
  linearCreateAttachmentTool,
  linearCreateCommentTool,
  linearCreateCustomerRequestTool,
  linearCreateCustomerStatusTool,
  linearCreateCustomerTierTool,
  linearCreateCustomerTool,
  linearCreateCycleTool,
  linearCreateFavoriteTool,
  linearCreateIssueRelationTool,
  linearCreateIssueTool,
  linearCreateLabelTool,
  linearCreateProjectLabelTool,
  linearCreateProjectMilestoneTool,
  linearCreateProjectStatusTool,
  linearCreateProjectTool,
  linearCreateProjectUpdateTool,
  linearCreateWorkflowStateTool,
  linearDeleteAttachmentTool,
  linearDeleteCommentTool,
  linearDeleteCustomerStatusTool,
  linearDeleteCustomerTierTool,
  linearDeleteCustomerTool,
  linearDeleteIssueRelationTool,
  linearDeleteIssueTool,
  linearDeleteProjectLabelTool,
  linearDeleteProjectMilestoneTool,
  linearDeleteProjectStatusTool,
  linearDeleteProjectTool,
  linearGetActiveCycleTool,
  linearGetCustomerTool,
  linearGetCycleTool,
  linearGetIssueTool,
  linearGetProjectTool,
  linearGetViewerTool,
  linearListAttachmentsTool,
  linearListCommentsTool,
  linearListCustomerRequestsTool,
  linearListCustomerStatusesTool,
  linearListCustomersTool,
  linearListCustomerTiersTool,
  linearListCyclesTool,
  linearListFavoritesTool,
  linearListIssueRelationsTool,
  linearListLabelsTool,
  linearListNotificationsTool,
  linearListProjectLabelsTool,
  linearListProjectMilestonesTool,
  linearListProjectStatusesTool,
  linearListProjectsTool,
  linearListProjectUpdatesTool,
  linearListTeamsTool,
  linearListUsersTool,
  linearListWorkflowStatesTool,
  linearMergeCustomersTool,
  linearReadIssuesTool,
  linearRemoveLabelFromIssueTool,
  linearRemoveLabelFromProjectTool,
  linearSearchIssuesTool,
  linearUnarchiveIssueTool,
  linearUpdateAttachmentTool,
  linearUpdateCommentTool,
  linearUpdateCustomerRequestTool,
  linearUpdateCustomerStatusTool,
  linearUpdateCustomerTierTool,
  linearUpdateCustomerTool,
  linearUpdateIssueTool,
  linearUpdateLabelTool,
  linearUpdateNotificationTool,
  linearUpdateProjectLabelTool,
  linearUpdateProjectMilestoneTool,
  linearUpdateProjectStatusTool,
  linearUpdateProjectTool,
  linearUpdateWorkflowStateTool,
} from '@/tools/linear'
import { llmChatTool } from '@/tools/llm'
import { memoryAddTool, memoryDeleteTool, memoryGetAllTool, memoryGetTool } from '@/tools/memory'
import {
  mongodbDeleteTool,
  mongodbExecuteTool,
  mongodbInsertTool,
  mongodbIntrospectTool,
  mongodbQueryTool,
  mongodbUpdateTool,
} from '@/tools/mongodb'
import {
  mysqlDeleteTool,
  mysqlExecuteTool,
  mysqlInsertTool,
  mysqlIntrospectTool,
  mysqlQueryTool,
  mysqlUpdateTool,
} from '@/tools/mysql'
import {
  notionAddDatabaseRowTool,
  notionCreateDatabaseTool,
  notionCreateDatabaseV2Tool,
  notionCreatePageTool,
  notionCreatePageV2Tool,
  notionQueryDatabaseTool,
  notionQueryDatabaseV2Tool,
  notionReadDatabaseTool,
  notionReadDatabaseV2Tool,
  notionReadTool,
  notionReadV2Tool,
  notionSearchTool,
  notionSearchV2Tool,
  notionUpdatePageV2Tool,
  notionWriteTool,
  notionWriteV2Tool,
} from '@/tools/notion'
import { openAIEmbeddingsTool, openAIImageTool } from '@/tools/openai'
import { parallelDeepResearchTool, parallelExtractTool, parallelSearchTool } from '@/tools/parallel'
import {
  postgresDeleteTool,
  postgresExecuteTool,
  postgresInsertTool,
  postgresIntrospectTool,
  postgresQueryTool,
  postgresUpdateTool,
} from '@/tools/postgresql'
import {
  redisCommandTool,
  redisDeleteTool,
  redisExistsTool,
  redisExpireTool,
  redisGetTool,
  redisHDelTool,
  redisHGetAllTool,
  redisHGetTool,
  redisHSetTool,
  redisIncrbyTool,
  redisIncrTool,
  redisKeysTool,
  redisLLenTool,
  redisLPopTool,
  redisLPushTool,
  redisLRangeTool,
  redisPersistTool,
  redisRPopTool,
  redisRPushTool,
  redisSetnxTool,
  redisSetTool,
  redisTtlTool,
} from '@/tools/redis'
import {
  s3CopyObjectTool,
  s3DeleteObjectTool,
  s3GetObjectTool,
  s3ListObjectsTool,
  s3PutObjectTool,
} from '@/tools/s3'
import { searchTool } from '@/tools/search'
import {
  sendGridAddContactsToListTool,
  sendGridAddContactTool,
  sendGridCreateListTool,
  sendGridCreateTemplateTool,
  sendGridCreateTemplateVersionTool,
  sendGridDeleteContactsTool,
  sendGridDeleteListTool,
  sendGridDeleteTemplateTool,
  sendGridGetContactTool,
  sendGridGetListTool,
  sendGridGetTemplateTool,
  sendGridListAllListsTool,
  sendGridListTemplatesTool,
  sendGridRemoveContactsFromListTool,
  sendGridSearchContactsTool,
  sendGridSendMailTool,
} from '@/tools/sendgrid'
import { serperSearchTool } from '@/tools/serper'
import {
  slackAddReactionTool,
  slackCanvasTool,
  slackCreateChannelCanvasTool,
  slackCreateConversationTool,
  slackDeleteMessageTool,
  slackDownloadTool,
  slackEditCanvasTool,
  slackEphemeralMessageTool,
  slackGetChannelInfoTool,
  slackGetMessageTool,
  slackGetThreadTool,
  slackGetUserPresenceTool,
  slackGetUserTool,
  slackInviteToConversationTool,
  slackListChannelsTool,
  slackListMembersTool,
  slackListUsersTool,
  slackMessageReaderTool,
  slackMessageTool,
  slackOpenViewTool,
  slackPublishViewTool,
  slackPushViewTool,
  slackRemoveReactionTool,
  slackUpdateMessageTool,
  slackUpdateViewTool,
} from '@/tools/slack'
import { sqsSendTool } from '@/tools/sqs'
import { stagehandAgentTool, stagehandExtractTool } from '@/tools/stagehand'
import {
  assemblyaiSttTool,
  assemblyaiSttV2Tool,
  deepgramSttTool,
  deepgramSttV2Tool,
  elevenLabsSttTool,
  elevenLabsSttV2Tool,
  geminiSttTool,
  geminiSttV2Tool,
  whisperSttTool,
  whisperSttV2Tool,
} from '@/tools/stt'
import {
  supabaseCountTool,
  supabaseDeleteTool,
  supabaseGetRowTool,
  supabaseInsertTool,
  supabaseIntrospectTool,
  supabaseQueryTool,
  supabaseRpcTool,
  supabaseStorageCopyTool,
  supabaseStorageCreateBucketTool,
  supabaseStorageCreateSignedUrlTool,
  supabaseStorageDeleteBucketTool,
  supabaseStorageDeleteTool,
  supabaseStorageDownloadTool,
  supabaseStorageGetPublicUrlTool,
  supabaseStorageListBucketsTool,
  supabaseStorageListTool,
  supabaseStorageMoveTool,
  supabaseStorageUploadTool,
  supabaseTextSearchTool,
  supabaseUpdateTool,
  supabaseUpsertTool,
  supabaseVectorSearchTool,
} from '@/tools/supabase'
import {
  tableBatchInsertRowsTool,
  tableCreateTool,
  tableDeleteRowsByFilterTool,
  tableDeleteRowTool,
  tableGetRowTool,
  tableGetSchemaTool,
  tableInsertRowTool,
  tableListTool,
  tableQueryRowsTool,
  tableUpdateRowsByFilterTool,
  tableUpdateRowTool,
  tableUpsertRowTool,
} from '@/tools/table'
import { tavilyCrawlTool, tavilyExtractTool, tavilyMapTool, tavilySearchTool } from '@/tools/tavily'
import {
  telegramDeleteMessageTool,
  telegramMessageTool,
  telegramSendAnimationTool,
  telegramSendAudioTool,
  telegramSendDocumentTool,
  telegramSendPhotoTool,
  telegramSendVideoTool,
} from '@/tools/telegram'
import { thinkingTool } from '@/tools/thinking'
import {
  azureTtsTool,
  cartesiaTtsTool,
  deepgramTtsTool,
  elevenLabsTtsUnifiedTool,
  googleTtsTool,
  openaiTtsTool,
  playhtTtsTool,
} from '@/tools/tts'
import type { ToolConfig } from '@/tools/types'
import { visionTool, visionToolV2 } from '@/tools/vision'

// Registry of all available tools
export const tools: Record<string, ToolConfig> = {
  browser_use_run_task: browserUseRunTaskTool,
  openai_embeddings: openAIEmbeddingsTool,
  http_request: httpRequestTool,
  webhook_request: webhookRequestTool,
  llm_chat: llmChatTool,
  function_execute: functionExecuteTool,
  vision_tool: visionTool,
  vision_tool_v2: visionToolV2,
  file_parser: fileParseTool,
  file_parser_v2: fileParserV2Tool,
  file_parser_v3: fileParserV3Tool,
  firecrawl_scrape: firecrawlScrapeTool,
  firecrawl_search: firecrawlSearchTool,
  firecrawl_crawl: firecrawlCrawlTool,
  firecrawl_map: firecrawlMapTool,
  firecrawl_extract: firecrawlExtractTool,
  firecrawl_agent: firecrawlAgentTool,
  guardrails_validate: guardrailsValidateTool,
  jina_read_url: jinaReadUrlTool,
  jina_search: jinaSearchTool,
  sendgrid_send_mail: sendGridSendMailTool,
  sendgrid_add_contact: sendGridAddContactTool,
  sendgrid_get_contact: sendGridGetContactTool,
  sendgrid_search_contacts: sendGridSearchContactsTool,
  sendgrid_delete_contacts: sendGridDeleteContactsTool,
  sendgrid_create_list: sendGridCreateListTool,
  sendgrid_get_list: sendGridGetListTool,
  sendgrid_list_all_lists: sendGridListAllListsTool,
  sendgrid_delete_list: sendGridDeleteListTool,
  sendgrid_add_contacts_to_list: sendGridAddContactsToListTool,
  sendgrid_remove_contacts_from_list: sendGridRemoveContactsFromListTool,
  sendgrid_create_template: sendGridCreateTemplateTool,
  sendgrid_get_template: sendGridGetTemplateTool,
  sendgrid_list_templates: sendGridListTemplatesTool,
  sendgrid_delete_template: sendGridDeleteTemplateTool,
  sendgrid_create_template_version: sendGridCreateTemplateVersionTool,
  jira_retrieve: jiraRetrieveTool,
  jira_update: jiraUpdateTool,
  jira_write: jiraWriteTool,
  jira_bulk_read: jiraBulkRetrieveTool,
  jira_delete_issue: jiraDeleteIssueTool,
  jira_assign_issue: jiraAssignIssueTool,
  jira_transition_issue: jiraTransitionIssueTool,
  jira_search_issues: jiraSearchIssuesTool,
  jira_add_comment: jiraAddCommentTool,
  jira_get_comments: jiraGetCommentsTool,
  jira_update_comment: jiraUpdateCommentTool,
  jira_delete_comment: jiraDeleteCommentTool,
  jira_get_attachments: jiraGetAttachmentsTool,
  jira_add_attachment: jiraAddAttachmentTool,
  jira_delete_attachment: jiraDeleteAttachmentTool,
  jira_add_worklog: jiraAddWorklogTool,
  jira_get_worklogs: jiraGetWorklogsTool,
  jira_update_worklog: jiraUpdateWorklogTool,
  jira_delete_worklog: jiraDeleteWorklogTool,
  jira_create_issue_link: jiraCreateIssueLinkTool,
  jira_delete_issue_link: jiraDeleteIssueLinkTool,
  jira_add_watcher: jiraAddWatcherTool,
  jira_remove_watcher: jiraRemoveWatcherTool,
  jira_get_users: jiraGetUsersTool,
  jira_search_users: jiraSearchUsersTool,
  parallel_search: parallelSearchTool,
  parallel_extract: parallelExtractTool,
  parallel_deep_research: parallelDeepResearchTool,
  redis_get: redisGetTool,
  redis_set: redisSetTool,
  redis_delete: redisDeleteTool,
  redis_keys: redisKeysTool,
  redis_command: redisCommandTool,
  redis_hset: redisHSetTool,
  redis_hget: redisHGetTool,
  redis_hgetall: redisHGetAllTool,
  redis_incr: redisIncrTool,
  redis_incrby: redisIncrbyTool,
  redis_expire: redisExpireTool,
  redis_ttl: redisTtlTool,
  redis_lpush: redisLPushTool,
  redis_lrange: redisLRangeTool,
  redis_exists: redisExistsTool,
  redis_setnx: redisSetnxTool,
  redis_rpush: redisRPushTool,
  redis_lpop: redisLPopTool,
  redis_rpop: redisRPopTool,
  redis_llen: redisLLenTool,
  redis_hdel: redisHDelTool,
  redis_persist: redisPersistTool,
  slack_message: slackMessageTool,
  slack_message_reader: slackMessageReaderTool,
  slack_list_channels: slackListChannelsTool,
  slack_list_members: slackListMembersTool,
  slack_list_users: slackListUsersTool,
  slack_get_user: slackGetUserTool,
  slack_get_message: slackGetMessageTool,
  slack_get_thread: slackGetThreadTool,
  slack_canvas: slackCanvasTool,
  slack_download: slackDownloadTool,
  slack_ephemeral_message: slackEphemeralMessageTool,
  slack_update_message: slackUpdateMessageTool,
  slack_delete_message: slackDeleteMessageTool,
  slack_add_reaction: slackAddReactionTool,
  slack_remove_reaction: slackRemoveReactionTool,
  slack_get_channel_info: slackGetChannelInfoTool,
  slack_get_user_presence: slackGetUserPresenceTool,
  slack_open_view: slackOpenViewTool,
  slack_update_view: slackUpdateViewTool,
  slack_push_view: slackPushViewTool,
  slack_publish_view: slackPublishViewTool,
  slack_edit_canvas: slackEditCanvasTool,
  slack_create_channel_canvas: slackCreateChannelCanvasTool,
  slack_create_conversation: slackCreateConversationTool,
  slack_invite_to_conversation: slackInviteToConversationTool,
  github_repo_info: githubRepoInfoTool,
  github_repo_info_v2: githubRepoInfoV2Tool,
  github_latest_commit: githubLatestCommitTool,
  github_latest_commit_v2: githubLatestCommitV2Tool,
  serper_search: serperSearchTool,
  tavily_search: tavilySearchTool,
  tavily_extract: tavilyExtractTool,
  tavily_crawl: tavilyCrawlTool,
  tavily_map: tavilyMapTool,
  supabase_query: supabaseQueryTool,
  supabase_insert: supabaseInsertTool,
  supabase_get_row: supabaseGetRowTool,
  supabase_update: supabaseUpdateTool,
  supabase_delete: supabaseDeleteTool,
  supabase_upsert: supabaseUpsertTool,
  supabase_count: supabaseCountTool,
  supabase_text_search: supabaseTextSearchTool,
  supabase_vector_search: supabaseVectorSearchTool,
  supabase_rpc: supabaseRpcTool,
  supabase_introspect: supabaseIntrospectTool,
  supabase_storage_upload: supabaseStorageUploadTool,
  supabase_storage_download: supabaseStorageDownloadTool,
  supabase_storage_list: supabaseStorageListTool,
  supabase_storage_delete: supabaseStorageDeleteTool,
  supabase_storage_move: supabaseStorageMoveTool,
  supabase_storage_copy: supabaseStorageCopyTool,
  supabase_storage_create_bucket: supabaseStorageCreateBucketTool,
  supabase_storage_list_buckets: supabaseStorageListBucketsTool,
  supabase_storage_delete_bucket: supabaseStorageDeleteBucketTool,
  supabase_storage_get_public_url: supabaseStorageGetPublicUrlTool,
  supabase_storage_create_signed_url: supabaseStorageCreateSignedUrlTool,
  notion_read: notionReadTool,
  notion_read_database: notionReadDatabaseTool,
  notion_write: notionWriteTool,
  notion_create_page: notionCreatePageTool,
  notion_query_database: notionQueryDatabaseTool,
  notion_search: notionSearchTool,
  notion_create_database: notionCreateDatabaseTool,
  // Notion V2 tools
  notion_read_v2: notionReadV2Tool,
  notion_read_database_v2: notionReadDatabaseV2Tool,
  notion_write_v2: notionWriteV2Tool,
  notion_create_page_v2: notionCreatePageV2Tool,
  notion_query_database_v2: notionQueryDatabaseV2Tool,
  notion_search_v2: notionSearchV2Tool,
  notion_create_database_v2: notionCreateDatabaseV2Tool,
  notion_update_page_v2: notionUpdatePageV2Tool,
  notion_add_database_row_v2: notionAddDatabaseRowTool,
  gmail_send: gmailSendTool,
  gmail_send_v2: gmailSendV2Tool,
  gmail_read: gmailReadTool,
  gmail_read_v2: gmailReadV2Tool,
  gmail_search: gmailSearchTool,
  gmail_search_v2: gmailSearchV2Tool,
  gmail_draft: gmailDraftTool,
  gmail_draft_v2: gmailDraftV2Tool,
  gmail_move: gmailMoveTool,
  gmail_move_v2: gmailMoveV2Tool,
  gmail_mark_read: gmailMarkReadTool,
  gmail_mark_read_v2: gmailMarkReadV2Tool,
  gmail_mark_unread: gmailMarkUnreadTool,
  gmail_mark_unread_v2: gmailMarkUnreadV2Tool,
  gmail_archive: gmailArchiveTool,
  gmail_archive_v2: gmailArchiveV2Tool,
  gmail_unarchive: gmailUnarchiveTool,
  gmail_unarchive_v2: gmailUnarchiveV2Tool,
  gmail_delete: gmailDeleteTool,
  gmail_delete_v2: gmailDeleteV2Tool,
  gmail_add_label: gmailAddLabelTool,
  gmail_add_label_v2: gmailAddLabelV2Tool,
  gmail_remove_label: gmailRemoveLabelTool,
  gmail_remove_label_v2: gmailRemoveLabelV2Tool,
  gmail_create_label_v2: gmailCreateLabelV2Tool,
  gmail_delete_draft_v2: gmailDeleteDraftV2Tool,
  gmail_delete_label_v2: gmailDeleteLabelV2Tool,
  gmail_get_draft_v2: gmailGetDraftV2Tool,
  gmail_get_thread_v2: gmailGetThreadV2Tool,
  gmail_list_drafts_v2: gmailListDraftsV2Tool,
  gmail_list_labels_v2: gmailListLabelsV2Tool,
  gmail_list_threads_v2: gmailListThreadsV2Tool,
  gmail_trash_thread_v2: gmailTrashThreadV2Tool,
  gmail_untrash_thread_v2: gmailUntrashThreadV2Tool,
  exa_search: exaSearchTool,
  exa_get_contents: exaGetContentsTool,
  exa_find_similar_links: exaFindSimilarLinksTool,
  exa_answer: exaAnswerTool,
  exa_research: exaResearchTool,
  mongodb_query: mongodbQueryTool,
  mongodb_insert: mongodbInsertTool,
  mongodb_update: mongodbUpdateTool,
  mongodb_delete: mongodbDeleteTool,
  mongodb_execute: mongodbExecuteTool,
  mongodb_introspect: mongodbIntrospectTool,
  mysql_query: mysqlQueryTool,
  mysql_insert: mysqlInsertTool,
  mysql_update: mysqlUpdateTool,
  mysql_delete: mysqlDeleteTool,
  mysql_execute: mysqlExecuteTool,
  mysql_introspect: mysqlIntrospectTool,
  github_pr: githubPrTool,
  github_pr_v2: githubPrV2Tool,
  github_comment: githubCommentTool,
  github_comment_v2: githubCommentV2Tool,
  github_issue_comment: githubIssueCommentTool,
  github_issue_comment_v2: githubIssueCommentV2Tool,
  github_list_issue_comments: githubListIssueCommentsTool,
  github_list_issue_comments_v2: githubListIssueCommentsV2Tool,
  github_update_comment: githubUpdateCommentTool,
  github_update_comment_v2: githubUpdateCommentV2Tool,
  github_delete_comment: githubDeleteCommentTool,
  github_delete_comment_v2: githubDeleteCommentV2Tool,
  github_list_pr_comments: githubListPRCommentsTool,
  github_list_pr_comments_v2: githubListPRCommentsV2Tool,
  github_create_pr: githubCreatePRTool,
  github_create_pr_v2: githubCreatePRV2Tool,
  github_update_pr: githubUpdatePRTool,
  github_update_pr_v2: githubUpdatePRV2Tool,
  github_merge_pr: githubMergePRTool,
  github_merge_pr_v2: githubMergePRV2Tool,
  github_list_prs: githubListPRsTool,
  github_list_prs_v2: githubListPRsV2Tool,
  github_get_pr_files: githubGetPRFilesTool,
  github_get_pr_files_v2: githubGetPRFilesV2Tool,
  github_close_pr: githubClosePRTool,
  github_close_pr_v2: githubClosePRV2Tool,
  github_request_reviewers: githubRequestReviewersTool,
  github_request_reviewers_v2: githubRequestReviewersV2Tool,
  github_get_file_content: githubGetFileContentTool,
  github_get_file_content_v2: githubGetFileContentV2Tool,
  github_create_file: githubCreateFileTool,
  github_create_file_v2: githubCreateFileV2Tool,
  github_update_file: githubUpdateFileTool,
  github_update_file_v2: githubUpdateFileV2Tool,
  github_delete_file: githubDeleteFileTool,
  github_delete_file_v2: githubDeleteFileV2Tool,
  github_get_tree: githubGetTreeTool,
  github_get_tree_v2: githubGetTreeV2Tool,
  github_list_branches: githubListBranchesTool,
  github_list_branches_v2: githubListBranchesV2Tool,
  github_get_branch: githubGetBranchTool,
  github_get_branch_v2: githubGetBranchV2Tool,
  github_create_branch: githubCreateBranchTool,
  github_create_branch_v2: githubCreateBranchV2Tool,
  github_delete_branch: githubDeleteBranchTool,
  github_delete_branch_v2: githubDeleteBranchV2Tool,
  github_get_branch_protection: githubGetBranchProtectionTool,
  github_get_branch_protection_v2: githubGetBranchProtectionV2Tool,
  github_update_branch_protection: githubUpdateBranchProtectionTool,
  github_update_branch_protection_v2: githubUpdateBranchProtectionV2Tool,
  github_create_issue: githubCreateIssueTool,
  github_create_issue_v2: githubCreateIssueV2Tool,
  github_update_issue: githubUpdateIssueTool,
  github_update_issue_v2: githubUpdateIssueV2Tool,
  github_list_issues: githubListIssuesTool,
  github_list_issues_v2: githubListIssuesV2Tool,
  github_get_issue: githubGetIssueTool,
  github_get_issue_v2: githubGetIssueV2Tool,
  github_close_issue: githubCloseIssueTool,
  github_close_issue_v2: githubCloseIssueV2Tool,
  github_add_labels: githubAddLabelsTool,
  github_add_labels_v2: githubAddLabelsV2Tool,
  github_remove_label: githubRemoveLabelTool,
  github_remove_label_v2: githubRemoveLabelV2Tool,
  github_add_assignees: githubAddAssigneesTool,
  github_add_assignees_v2: githubAddAssigneesV2Tool,
  github_create_release: githubCreateReleaseTool,
  github_create_release_v2: githubCreateReleaseV2Tool,
  github_update_release: githubUpdateReleaseTool,
  github_update_release_v2: githubUpdateReleaseV2Tool,
  github_list_releases: githubListReleasesTool,
  github_list_releases_v2: githubListReleasesV2Tool,
  github_get_release: githubGetReleaseTool,
  github_get_release_v2: githubGetReleaseV2Tool,
  github_delete_release: githubDeleteReleaseTool,
  github_delete_release_v2: githubDeleteReleaseV2Tool,
  github_list_workflows: githubListWorkflowsTool,
  github_list_workflows_v2: githubListWorkflowsV2Tool,
  github_get_workflow: githubGetWorkflowTool,
  github_get_workflow_v2: githubGetWorkflowV2Tool,
  github_trigger_workflow: githubTriggerWorkflowTool,
  github_trigger_workflow_v2: githubTriggerWorkflowV2Tool,
  github_list_workflow_runs: githubListWorkflowRunsTool,
  github_list_workflow_runs_v2: githubListWorkflowRunsV2Tool,
  github_get_workflow_run: githubGetWorkflowRunTool,
  github_get_workflow_run_v2: githubGetWorkflowRunV2Tool,
  github_cancel_workflow_run: githubCancelWorkflowRunTool,
  github_cancel_workflow_run_v2: githubCancelWorkflowRunV2Tool,
  github_rerun_workflow: githubRerunWorkflowTool,
  github_rerun_workflow_v2: githubRerunWorkflowV2Tool,
  github_list_projects: githubListProjectsTool,
  github_list_projects_v2: githubListProjectsV2Tool,
  github_get_project: githubGetProjectTool,
  github_get_project_v2: githubGetProjectV2Tool,
  github_create_project: githubCreateProjectTool,
  github_create_project_v2: githubCreateProjectV2Tool,
  github_update_project: githubUpdateProjectTool,
  github_update_project_v2: githubUpdateProjectV2Tool,
  github_delete_project: githubDeleteProjectTool,
  github_delete_project_v2: githubDeleteProjectV2Tool,
  // GitHub - Search
  github_search_code: githubSearchCodeTool,
  github_search_code_v2: githubSearchCodeV2Tool,
  github_search_commits: githubSearchCommitsTool,
  github_search_commits_v2: githubSearchCommitsV2Tool,
  github_search_issues: githubSearchIssuesTool,
  github_search_issues_v2: githubSearchIssuesV2Tool,
  github_search_repos: githubSearchReposTool,
  github_search_repos_v2: githubSearchReposV2Tool,
  github_search_users: githubSearchUsersTool,
  github_search_users_v2: githubSearchUsersV2Tool,
  // GitHub - Commits
  github_list_commits: githubListCommitsTool,
  github_list_commits_v2: githubListCommitsV2Tool,
  github_get_commit: githubGetCommitTool,
  github_get_commit_v2: githubGetCommitV2Tool,
  github_compare_commits: githubCompareCommitsTool,
  github_compare_commits_v2: githubCompareCommitsV2Tool,
  // GitHub - Gists
  github_create_gist: githubCreateGistTool,
  github_create_gist_v2: githubCreateGistV2Tool,
  github_get_gist: githubGetGistTool,
  github_get_gist_v2: githubGetGistV2Tool,
  github_list_gists: githubListGistsTool,
  github_list_gists_v2: githubListGistsV2Tool,
  github_update_gist: githubUpdateGistTool,
  github_update_gist_v2: githubUpdateGistV2Tool,
  github_delete_gist: githubDeleteGistTool,
  github_delete_gist_v2: githubDeleteGistV2Tool,
  github_fork_gist: githubForkGistTool,
  github_fork_gist_v2: githubForkGistV2Tool,
  github_star_gist: githubStarGistTool,
  github_star_gist_v2: githubStarGistV2Tool,
  github_unstar_gist: githubUnstarGistTool,
  github_unstar_gist_v2: githubUnstarGistV2Tool,
  // GitHub - Forks
  github_fork_repo: githubForkRepoTool,
  github_fork_repo_v2: githubForkRepoV2Tool,
  github_list_forks: githubListForksTool,
  github_list_forks_v2: githubListForksV2Tool,
  // GitHub - Milestones
  github_create_milestone: githubCreateMilestoneTool,
  github_create_milestone_v2: githubCreateMilestoneV2Tool,
  github_get_milestone: githubGetMilestoneTool,
  github_get_milestone_v2: githubGetMilestoneV2Tool,
  github_list_milestones: githubListMilestonesTool,
  github_list_milestones_v2: githubListMilestonesV2Tool,
  github_update_milestone: githubUpdateMilestoneTool,
  github_update_milestone_v2: githubUpdateMilestoneV2Tool,
  github_delete_milestone: githubDeleteMilestoneTool,
  github_delete_milestone_v2: githubDeleteMilestoneV2Tool,
  // GitHub - Reactions
  github_create_issue_reaction: githubCreateIssueReactionTool,
  github_create_issue_reaction_v2: githubCreateIssueReactionV2Tool,
  github_delete_issue_reaction: githubDeleteIssueReactionTool,
  github_delete_issue_reaction_v2: githubDeleteIssueReactionV2Tool,
  github_create_comment_reaction: githubCreateCommentReactionTool,
  github_create_comment_reaction_v2: githubCreateCommentReactionV2Tool,
  github_delete_comment_reaction: githubDeleteCommentReactionTool,
  github_delete_comment_reaction_v2: githubDeleteCommentReactionV2Tool,
  // GitHub - Stars
  github_star_repo: githubStarRepoTool,
  github_star_repo_v2: githubStarRepoV2Tool,
  github_unstar_repo: githubUnstarRepoTool,
  github_unstar_repo_v2: githubUnstarRepoV2Tool,
  github_check_star: githubCheckStarTool,
  github_check_star_v2: githubCheckStarV2Tool,
  github_list_stargazers: githubListStargazersTool,
  github_list_stargazers_v2: githubListStargazersV2Tool,
  postgresql_query: postgresQueryTool,
  postgresql_insert: postgresInsertTool,
  postgresql_update: postgresUpdateTool,
  postgresql_delete: postgresDeleteTool,
  postgresql_execute: postgresExecuteTool,
  postgresql_introspect: postgresIntrospectTool,
  discord_send_message: discordSendMessageTool,
  discord_get_messages: discordGetMessagesTool,
  discord_get_server: discordGetServerTool,
  discord_get_user: discordGetUserTool,
  discord_edit_message: discordEditMessageTool,
  discord_delete_message: discordDeleteMessageTool,
  discord_add_reaction: discordAddReactionTool,
  discord_remove_reaction: discordRemoveReactionTool,
  discord_pin_message: discordPinMessageTool,
  discord_unpin_message: discordUnpinMessageTool,
  discord_create_thread: discordCreateThreadTool,
  discord_join_thread: discordJoinThreadTool,
  discord_leave_thread: discordLeaveThreadTool,
  discord_archive_thread: discordArchiveThreadTool,
  discord_create_channel: discordCreateChannelTool,
  discord_update_channel: discordUpdateChannelTool,
  discord_delete_channel: discordDeleteChannelTool,
  discord_get_channel: discordGetChannelTool,
  discord_create_role: discordCreateRoleTool,
  discord_update_role: discordUpdateRoleTool,
  discord_delete_role: discordDeleteRoleTool,
  discord_assign_role: discordAssignRoleTool,
  discord_remove_role: discordRemoveRoleTool,
  discord_kick_member: discordKickMemberTool,
  discord_ban_member: discordBanMemberTool,
  discord_unban_member: discordUnbanMemberTool,
  discord_get_member: discordGetMemberTool,
  discord_update_member: discordUpdateMemberTool,
  discord_create_invite: discordCreateInviteTool,
  discord_get_invite: discordGetInviteTool,
  discord_delete_invite: discordDeleteInviteTool,
  discord_create_webhook: discordCreateWebhookTool,
  discord_execute_webhook: discordExecuteWebhookTool,
  discord_get_webhook: discordGetWebhookTool,
  discord_delete_webhook: discordDeleteWebhookTool,
  openai_image: openAIImageTool,
  linear_read_issues: linearReadIssuesTool,
  linear_create_issue: linearCreateIssueTool,
  linear_get_issue: linearGetIssueTool,
  linear_update_issue: linearUpdateIssueTool,
  linear_archive_issue: linearArchiveIssueTool,
  linear_unarchive_issue: linearUnarchiveIssueTool,
  linear_delete_issue: linearDeleteIssueTool,
  linear_add_label_to_issue: linearAddLabelToIssueTool,
  linear_remove_label_from_issue: linearRemoveLabelFromIssueTool,
  linear_search_issues: linearSearchIssuesTool,
  linear_create_comment: linearCreateCommentTool,
  linear_update_comment: linearUpdateCommentTool,
  linear_delete_comment: linearDeleteCommentTool,
  linear_list_comments: linearListCommentsTool,
  linear_list_projects: linearListProjectsTool,
  linear_get_project: linearGetProjectTool,
  linear_create_project: linearCreateProjectTool,
  linear_update_project: linearUpdateProjectTool,
  linear_archive_project: linearArchiveProjectTool,
  linear_list_users: linearListUsersTool,
  linear_list_teams: linearListTeamsTool,
  linear_get_viewer: linearGetViewerTool,
  linear_list_labels: linearListLabelsTool,
  linear_create_label: linearCreateLabelTool,
  linear_update_label: linearUpdateLabelTool,
  linear_archive_label: linearArchiveLabelTool,
  linear_list_workflow_states: linearListWorkflowStatesTool,
  linear_create_workflow_state: linearCreateWorkflowStateTool,
  linear_update_workflow_state: linearUpdateWorkflowStateTool,
  linear_list_cycles: linearListCyclesTool,
  linear_get_cycle: linearGetCycleTool,
  linear_create_cycle: linearCreateCycleTool,
  linear_get_active_cycle: linearGetActiveCycleTool,
  linear_create_attachment: linearCreateAttachmentTool,
  linear_list_attachments: linearListAttachmentsTool,
  linear_update_attachment: linearUpdateAttachmentTool,
  linear_delete_attachment: linearDeleteAttachmentTool,
  linear_create_issue_relation: linearCreateIssueRelationTool,
  linear_list_issue_relations: linearListIssueRelationsTool,
  linear_delete_issue_relation: linearDeleteIssueRelationTool,
  linear_create_favorite: linearCreateFavoriteTool,
  linear_list_favorites: linearListFavoritesTool,
  linear_create_project_update: linearCreateProjectUpdateTool,
  linear_list_project_updates: linearListProjectUpdatesTool,
  linear_list_notifications: linearListNotificationsTool,
  linear_update_notification: linearUpdateNotificationTool,
  linear_create_customer: linearCreateCustomerTool,
  linear_list_customers: linearListCustomersTool,
  linear_create_customer_request: linearCreateCustomerRequestTool,
  linear_update_customer_request: linearUpdateCustomerRequestTool,
  linear_list_customer_requests: linearListCustomerRequestsTool,
  linear_get_customer: linearGetCustomerTool,
  linear_update_customer: linearUpdateCustomerTool,
  linear_delete_customer: linearDeleteCustomerTool,
  linear_merge_customers: linearMergeCustomersTool,
  linear_create_customer_status: linearCreateCustomerStatusTool,
  linear_update_customer_status: linearUpdateCustomerStatusTool,
  linear_delete_customer_status: linearDeleteCustomerStatusTool,
  linear_list_customer_statuses: linearListCustomerStatusesTool,
  linear_create_customer_tier: linearCreateCustomerTierTool,
  linear_update_customer_tier: linearUpdateCustomerTierTool,
  linear_delete_customer_tier: linearDeleteCustomerTierTool,
  linear_list_customer_tiers: linearListCustomerTiersTool,
  linear_delete_project: linearDeleteProjectTool,
  linear_create_project_label: linearCreateProjectLabelTool,
  linear_update_project_label: linearUpdateProjectLabelTool,
  linear_delete_project_label: linearDeleteProjectLabelTool,
  linear_list_project_labels: linearListProjectLabelsTool,
  linear_add_label_to_project: linearAddLabelToProjectTool,
  linear_remove_label_from_project: linearRemoveLabelFromProjectTool,
  linear_create_project_milestone: linearCreateProjectMilestoneTool,
  linear_update_project_milestone: linearUpdateProjectMilestoneTool,
  linear_delete_project_milestone: linearDeleteProjectMilestoneTool,
  linear_list_project_milestones: linearListProjectMilestonesTool,
  linear_create_project_status: linearCreateProjectStatusTool,
  linear_update_project_status: linearUpdateProjectStatusTool,
  linear_delete_project_status: linearDeleteProjectStatusTool,
  linear_list_project_statuses: linearListProjectStatusesTool,
  thinking_tool: thinkingTool,
  stagehand_extract: stagehandExtractTool,
  stagehand_agent: stagehandAgentTool,
  memory_add: memoryAddTool,
  memory_get: memoryGetTool,
  memory_get_all: memoryGetAllTool,
  memory_delete: memoryDeleteTool,
  knowledge_search: knowledgeSearchTool,
  knowledge_upload_chunk: knowledgeUploadChunkTool,
  knowledge_create_document: knowledgeCreateDocumentTool,
  knowledge_list_tags: knowledgeListTagsTool,
  knowledge_list_documents: knowledgeListDocumentsTool,
  knowledge_get_document: knowledgeGetDocumentTool,
  knowledge_delete_document: knowledgeDeleteDocumentTool,
  knowledge_list_chunks: knowledgeListChunksTool,
  knowledge_update_chunk: knowledgeUpdateChunkTool,
  knowledge_delete_chunk: knowledgeDeleteChunkTool,
  knowledge_list_connectors: knowledgeListConnectorsTool,
  knowledge_get_connector: knowledgeGetConnectorTool,
  knowledge_trigger_sync: knowledgeTriggerSyncTool,
  knowledge_upsert_document: knowledgeUpsertDocumentTool,
  search_tool: searchTool,
  elevenlabs_tts: elevenLabsTtsTool,
  stt_whisper: whisperSttTool,
  stt_whisper_v2: whisperSttV2Tool,
  stt_deepgram: deepgramSttTool,
  stt_deepgram_v2: deepgramSttV2Tool,
  stt_elevenlabs: elevenLabsSttTool,
  stt_elevenlabs_v2: elevenLabsSttV2Tool,
  stt_assemblyai: assemblyaiSttTool,
  stt_assemblyai_v2: assemblyaiSttV2Tool,
  stt_gemini: geminiSttTool,
  stt_gemini_v2: geminiSttV2Tool,
  tts_openai: openaiTtsTool,
  tts_deepgram: deepgramTtsTool,
  tts_elevenlabs: elevenLabsTtsUnifiedTool,
  tts_cartesia: cartesiaTtsTool,
  tts_google: googleTtsTool,
  tts_azure: azureTtsTool,
  tts_playht: playhtTtsTool,
  s3_get_object: s3GetObjectTool,
  s3_put_object: s3PutObjectTool,
  s3_list_objects: s3ListObjectsTool,
  s3_delete_object: s3DeleteObjectTool,
  s3_copy_object: s3CopyObjectTool,
  telegram_message: telegramMessageTool,
  telegram_delete_message: telegramDeleteMessageTool,
  telegram_send_audio: telegramSendAudioTool,
  telegram_send_animation: telegramSendAnimationTool,
  telegram_send_photo: telegramSendPhotoTool,
  telegram_send_video: telegramSendVideoTool,
  telegram_send_document: telegramSendDocumentTool,
  sqs_send: sqsSendTool,
  table_create: tableCreateTool,
  table_list: tableListTool,
  table_insert_row: tableInsertRowTool,
  table_batch_insert_rows: tableBatchInsertRowsTool,
  table_upsert_row: tableUpsertRowTool,
  table_update_row: tableUpdateRowTool,
  table_update_rows_by_filter: tableUpdateRowsByFilterTool,
  table_delete_row: tableDeleteRowTool,
  table_delete_rows_by_filter: tableDeleteRowsByFilterTool,
  table_query_rows: tableQueryRowsTool,
  table_get_row: tableGetRowTool,
  table_get_schema: tableGetSchemaTool,
}
